#Declare Variables
NAME= "JUAN DELACRUZ"
AGE= "20"
FAVPROG= "PHYTON"

echo "ENTER YOUR NAME: "
read NAME

echo "ENTER YOUR AGE:"
read AGE

echo "ENTER YOUR FAVORITE PROGRAMMING LANGUAGE:"
read FAVPROG

echo "THANK YOU $NAME, YOU ARE $AGE YEARS OLD & YOUR FAVORITE PROGRAMMING LANGUAGE IS $FAVPROG.
